export type Lang = 'en' | 'ur';

export const translations = {
  en: {
    // ── Nav ──────────────────────────────────────────────────────────────────
    dashboard: 'Dashboard',
    farmers: 'Farmers',
    retailers: 'Retailers',
    collection: 'Collection',
    delivery: 'Delivery',
    marketRates: 'Market Rates',
    billing: 'Billing & Invoices',
    payments: 'Payments',
    reports: 'Reports',
    accounts: 'Accounts',
    transport: 'Transport',
    staff: 'Staff',
    users: 'Users',
    settings: 'Settings',
    scheduler: 'Scheduler',
    notifications: 'Notifications',
    signOut: 'Sign out',

    // ── Settings tabs ─────────────────────────────────────────────────────────
    organization: 'Organization',
    subscription: 'Subscription',

    // ── Auth ─────────────────────────────────────────────────────────────────
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    signInToAccount: 'Sign in to your account',
    inviteOnly: 'Access is by invitation only. Contact your administrator.',
    invalidCredentials: 'Invalid email or password',

    // ── Common ────────────────────────────────────────────────────────────────
    save: 'Save Settings',
    saving: 'Saving…',
    saved: 'Saved!',
    loading: 'Loading…',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    clearFilters: 'Clear',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    close: 'Close',
    noData: 'No data available.',
    from: 'From',
    to: 'To',
    all: 'All',
    date: 'Date',
    amount: 'Amount',
    quantity: 'Quantity',
    rate: 'Rate',
    total: 'Total',
    net: 'Net',
    paid: 'Paid',
    outstanding: 'Outstanding',
    viewAll: 'View All',
    refresh: 'Refresh',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    of: 'of',
    session: 'Session',
    actions: 'Actions',
    sortAsc: 'Sort Ascending',
    sortDesc: 'Sort Descending',
    noResults: 'No results found.',
    rowsPerPage: 'Rows per page',

    // ── Users page ────────────────────────────────────────────────────────────
    inviteUser: 'Invite User',
    name: 'Name',
    role: 'Role',
    status: 'Status',
    blocked: 'Blocked',
    active: 'Active',
    pending: 'Pending Invite',
    block: 'Block',
    unblock: 'Unblock',
    resetPassword: 'Reset Password',
    removeUser: 'Remove',
    copyLink: 'Copy Link',
    linkCopied: 'Copied!',
    you: 'you',
    usersPageTitle: 'Users',
    usersPageDesc: 'Manage team access — invite, block, or update roles',
    joinedDate: 'Joined',
    permissions: 'Permissions',
    permissionsDesc: 'Control which pages this user can access',
    filterByRole: 'Filter by role',
    filterByStatus: 'Filter by status',
    savePermissions: 'Save Permissions',
    savingPermissions: 'Saving…',
    permissionsSaved: 'Saved!',
    allPagesAccess: 'All pages allowed by default for this role',
    staffInfo: 'Staff Info',
    department: 'Department',
    position: 'Position',

    // ── Accept invite ─────────────────────────────────────────────────────────
    acceptInviteTitle: 'Set Your Password',
    acceptInviteSubtitle: 'Choose a secure password to activate your account.',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    activateAccount: 'Activate Account',
    activating: 'Activating…',
    passwordMismatch: 'Passwords do not match.',
    invalidToken: 'Invalid or expired invite link.',

    // ── Branding / Settings ───────────────────────────────────────────────────
    brandName: 'Brand Name',
    tagline: 'Tagline',
    primaryColor: 'Primary Color',
    accentColor: 'Accent Color',
    logo: 'Logo',
    businessDetails: 'Business Details',
    address: 'Address',
    phone: 'Phone',
    websiteLabel: 'Website',
    taxId: 'Tax / NTN ID',
    bankDetails: 'Bank Details',
    bankName: 'Bank Name',
    accountNo: 'Account No.',
    iban: 'IBAN',
    invoiceTemplate: 'Invoice Template',
    signature: 'Authorized Signature',
    invoicePreview: 'Invoice Header Preview',

    // ── Dashboard ─────────────────────────────────────────────────────────────
    live: 'Live',
    collectedStat: 'Collected',
    deliveredStat: 'Delivered',
    receivablesStat: 'Receivables',
    payablesStat: 'Payables',
    maundsUnit: 'Mns',
    maundsFull: 'Maunds',
    trend7Day: '7-Day Collection vs Delivery',
    morning: 'Morning',
    evening: 'Evening',
    avgRate: 'Avg',
    collectionProgress: 'Collection Progress',
    deliveryProgress: 'Delivery Progress',
    contractedLabel: 'contracted',
    committedLabel: 'committed',
    todayBalance: "Today's Balance",
    collectedMinusDelivered: 'Collected − Delivered',
    netFinancial: 'Net Financial',
    outstandingAllTime: 'Outstanding (All Time)',
    viewMarketRates: 'View Market Rates →',
    perMaund: 'PKR/Mun',
    farmerCountLabel: 'farmers',
    retailerCountLabel: 'retailers',
    unpaidLabel: 'unpaid',
    selectDateLabel: 'View data for date',
    dashboardFor: 'Dashboard for',

    // ── Market Rates ──────────────────────────────────────────────────────────
    latestMorningRate: 'Latest Morning Rate',
    latestEveningRate: 'Latest Evening Rate',
    setMarketRate: 'Set Market Rate',
    ratePKRMun: 'Rate (PKR/Mun)',
    rateHistory: 'Rate History',
    setRate: 'Set Rate',
    noRatesYet: 'No rates set yet.',
    marketTrend: 'Market Rate Trend (Last 30 Days)',
    ratePlaceholder: 'e.g. 9000',

    // ── Accounts ──────────────────────────────────────────────────────────────
    profitLoss: 'P&L',
    balanceSheet: 'Balance Sheet',
    totalRevenue: 'Total Revenue',
    grossProfit: 'Gross Profit',
    netProfit: 'Net Profit',
    totalCosts: 'Total Costs',
    revenueSectionTitle: 'Revenue',
    costsSectionTitle: 'Costs',
    summarySection: 'Summary',
    farmerPayouts: 'Farmer Payouts',
    staffSalaries: 'Staff Salaries (est.)',
    cashInHand: 'cash in hand',
    yetToCollect: 'yet to collect',
    assetsReceivables: 'Assets / Receivables',
    liabilitiesPayables: 'Liabilities / Payables',
    payrollSection: 'Payroll',
    activeStaff: 'Active Staff',
    monthlyPayroll: 'Monthly Payroll',
    netPositionLabel: 'Net Position (Receivables − Payables)',
    revenueVsCosts: 'Revenue vs Costs',
    assetsVsLiabilities: 'Assets vs Liabilities',
    grossProfitVsRevenue: 'Gross Profit (Revenue − Farmer Costs)',
    netProfitAfterSalaries: 'Net Profit (After Staff Salaries)',
    retailerReceivablesLabel: 'Retailer Receivables (Unpaid)',
    totalRevenueBilled: 'Total Revenue Billed',
    revenueCollected: 'Revenue Collected',
    farmerPayablesLabel: 'Farmer Payables (Unpaid)',
    totalFarmerCostsBilled: 'Total Farmer Costs Billed',
    farmerCostsPaid: 'Farmer Costs Paid',
    members: 'members',
    invoicesLabel: 'invoices',
    retailerInvoicesBilled: 'Retailer Invoices (Billed)',
    collectedPaid: 'Collected (Paid)',
    staffSalariesEst: 'Staff Salaries (est.)',

    // ── Notifications ─────────────────────────────────────────────────────────
    notificationsTitle: 'Notifications',
    notificationsDesc: 'Messages sent via WhatsApp, Email, and SMS',
    channelType: 'Channel',
    whatsapp: 'WhatsApp',
    sms: 'SMS',
    markRead: 'Mark Read',
    markAllRead: 'Mark All Read',
    noNotifications: 'No notifications yet.',
    notifAll: 'All',
    notifUnread: 'Unread',
    message: 'Message',
    recipient: 'Recipient',
    sentAt: 'Sent At',
    readStatus: 'Read',

    // ── Farmers ───────────────────────────────────────────────────────────────
    addFarmer: 'Add Farmer',
    editFarmer: 'Edit Farmer',
    farmerDetails: 'Farmer Details',
    contractedQty: 'Contracted Qty (Mns/day)',
    fixedRate: 'Fixed Rate (PKR/Mun)',
    farmerName: 'Farmer Name',
    village: 'Village / Area',
    cnic: 'CNIC',
    noFarmers: 'No farmers found.',
    dailyQty: 'Daily Qty',
    contractRate: 'Contract Rate',

    // ── Retailers ─────────────────────────────────────────────────────────────
    addRetailer: 'Add Retailer',
    editRetailer: 'Edit Retailer',
    retailerDetails: 'Retailer Details',
    committedQty: 'Committed Qty (Mns/day)',
    retailerName: 'Retailer Name',
    shopName: 'Shop Name',
    area: 'Area',
    noRetailers: 'No retailers found.',

    // ── Collection / Delivery ─────────────────────────────────────────────────
    addCollection: 'Add Collection',
    addDelivery: 'Add Delivery',
    fat: 'Fat %',
    waterAdded: 'Water Added',
    collectionHistory: 'Collection History',
    deliveryHistory: 'Delivery History',
    noEntries: 'No entries found.',
    selectFarmer: 'Select Farmer',
    selectRetailer: 'Select Retailer',
    farmer: 'Farmer',
    retailer: 'Retailer',
    maunds: 'Maunds',
    litres: 'Litres',
    quality: 'Quality',
    passed: 'Passed',
    failed: 'Failed',

    // ── Billing ───────────────────────────────────────────────────────────────
    farmerInvoices: 'Farmer Invoices',
    retailerInvoices: 'Retailer Invoices',
    generateInvoice: 'Generate Invoices',
    generating: 'Generating…',
    markAsPaid: 'Mark as Paid',
    paymentMode: 'Payment Mode',
    paymentRef: 'Payment Reference',
    paymentDate: 'Payment Date',
    invoiceNo: 'Invoice #',
    invoiceDate: 'Invoice Date',
    dueDate: 'Due Date',
    penalty: 'Penalty',
    bonus: 'Bonus / Reward',
    netPayable: 'Net Payable',
    invoiceStatus: 'Status',
    noInvoices: 'No invoices found.',
    paidInvoices: 'Paid',
    unpaidInvoices: 'Unpaid',
    totalBilled: 'Total Billed',
    totalPaid: 'Total Paid',
    totalOutstanding: 'Total Outstanding',
    netPayableWords: 'Net Payable in Words',
    dateWise: 'Date-wise Breakdown',
    morningQty: 'Morning Qty',
    eveningQty: 'Evening Qty',
    marketRateApplied: 'Market Rate Applied',
    fixedRateApplied: 'Fixed Rate Applied',
    penaltyApplied: 'Penalty Applied',
    rewardApplied: 'Reward Applied',
    penaltyQty: 'Penalty Qty',
    rewardQty: 'Reward Qty',

    // ── Payments ──────────────────────────────────────────────────────────────
    addPayment: 'Add Payment',
    paymentDirection: 'Direction',
    incoming: 'Incoming',
    outgoing: 'Outgoing',
    noPayments: 'No payments found.',
    paymentSummary: 'Payment Summary',
    totalIncoming: 'Total Incoming',
    totalOutgoing: 'Total Outgoing',
    balance: 'Balance',

    // ── Reports ───────────────────────────────────────────────────────────────
    generateReport: 'Generate Report',
    selectReport: 'Select Report Type',
    dateRange: 'Date Range',
    collectionReport: 'Collection Report',
    deliveryReport: 'Delivery Report',
    qualityReport: 'Quality Report',
    paymentsReport: 'Payments Report',
    receivablesReport: 'Receivables Report',
    payablesReport: 'Payables Report',
    balanceReport: 'Balance Report',
    noReport: 'Select a report type and date range to generate.',
    downloading: 'Downloading…',

    // ── Transport ─────────────────────────────────────────────────────────────
    addTrip: 'Add Trip',
    tripDate: 'Trip Date',
    driver: 'Driver',
    route: 'Route',
    stops: 'Stops',
    tripStatus: 'Status',
    addTank: 'Add Tank',
    tankCapacity: 'Capacity (Litres)',
    noTrips: 'No trips found.',
    noTanks: 'No tanks found.',

    // ── Staff ─────────────────────────────────────────────────────────────────
    addStaff: 'Add Staff',
    staffName: 'Staff Name',
    staffRole: 'Staff Role',
    salary: 'Monthly Salary',
    joiningDate: 'Joining Date',
    noStaff: 'No staff found.',
    payroll: 'Payroll',
    totalPayroll: 'Total Payroll',

    // ── Scheduler ─────────────────────────────────────────────────────────────
    addSchedule: 'Add Schedule',
    frequency: 'Frequency',
    nextRun: 'Next Run',
    scheduleType: 'Schedule Type',
    noSchedules: 'No schedules found.',
    toggleSchedule: 'Toggle',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    enabled: 'Enabled',
    disabled: 'Disabled',
    lastRun: 'Last Run',

    // ── Farmers / Retailers ───────────────────────────────────────────────────
    inactive: 'Inactive',
    deactivate: 'Deactivate',
    contractPeriod: 'Contract Period',
    ongoing: 'Ongoing',
    phoneEmail: 'Phone / Email',
    newFarmer: 'New Farmer',
    updateFarmer: 'Update Farmer',
    saveFarmer: 'Save Farmer',
    newRetailer: 'New Retailer',
    updateRetailer: 'Update Retailer',
    saveRetailer: 'Save Retailer',
    perDay: '/day',
    activeCount: 'active',
    deactivateConfirm: 'Deactivate this record?',

    // ── Billing extra ─────────────────────────────────────────────────────────
    allFarmers: 'All Farmers',
    allRetailers: 'All Retailers',
    allModes: 'All Modes',
    totalInvoices: 'Total Invoices',
    totalAmount: 'Total Amount (PKR)',
    baseAmount: 'Base Amount',
    shortfall: 'Shortfall',
    excess: 'Excess',
    surcharge: 'Surcharge',
    exportPDFBtn: 'PDF',

    // ── Payments extra ────────────────────────────────────────────────────────
    note: 'Note',
    paymentType: 'Type',
    cash: 'Cash',
    cheque: 'Cheque',
    bankTransfer: 'Bank Transfer',
    online: 'Online',

    // ── Reports extra ─────────────────────────────────────────────────────────
    morningCollection: 'Morning Collection',
    eveningCollection: 'Evening Collection',
    combinedCollection: 'Combined Collection',
    morningDelivery: 'Morning Delivery',
    eveningDelivery: 'Evening Delivery',
    combinedDelivery: 'Combined Delivery',
    milkQuality: 'Milk Quality',
    passRate: 'Pass Rate',
    avgFat: 'Avg. Fat %',
    totalEntries: 'Total Entries',
    receivablesPayables: 'Receivables & Payables',
    balanceReportLabel: 'Balance Report',

    // ── Transport extra ───────────────────────────────────────────────────────
    tripNumber: 'Trip #',
    vehicle: 'Vehicle',
    inProgress: 'In Progress',
    completed: 'Completed',
    newTrip: 'New Trip',
    tankLabel: 'Tank',
    capacity: 'Capacity (L)',
    newTank: 'New Tank',

    // ── Staff extra ───────────────────────────────────────────────────────────
    updateStaff: 'Update Staff',
    saveStaff: 'Save Staff',
    newStaff: 'New Staff Member',
    phoneLabel: 'Phone',

    // ── Settings extra ────────────────────────────────────────────────────────
    logoUrl: 'Logo URL',
    invoiceFooterLabel: 'Invoice Footer',
    invoiceHeaderLabel: 'Invoice Header',
    signatureTitle: 'Signature Title',
    signatureName: 'Signature Name',
    settingsTitle: 'Settings',
    orgTab: 'Organization',
    subTab: 'Subscription',
    planLabel: 'Plan',
    renewsLabel: 'Renews',

    // ── Collection / Delivery extra ───────────────────────────────────────────
    bulkEntry: "Today's Entry",
    saveEntries: 'Save Entries',
    savedCount: 'saved',
    skippedCount: 'skipped',
    totalMorning: 'Total Morning',
    totalEvening: 'Total Evening',
    grandTotal: 'Grand Total',
    historyTab: 'History',
    inputTab: 'Input',

    // ── Social login ──────────────────────────────────────────────────────────
    orContinueWith: 'Or continue with',
    signInWithGoogle: 'Continue with Google',
    signInWithFacebook: 'Continue with Facebook',
    yes: 'Yes',
    no: 'No',

    // ── Payments page extras ──────────────────────────────────────────────────
    recordPayment: 'Record Payment',
    recordNewPayment: 'Record New Payment',
    savePayment: 'Save Payment',
    referenceNo: 'Reference / Cheque No.',
    notes: 'Notes',
    allTypes: 'All Types',
    netPosition: 'Net Position',
    party: 'Party',
    deletePayment: 'Delete Payment?',
    cannotUndo: 'This action cannot be undone.',
    gift: 'Gift',
    other: 'Other',
    allDirections: 'All Directions',

    // ── Staff page extras ─────────────────────────────────────────────────────
    totalActiveStaff: 'Total Active Staff',
    monthlyPayrollPKR: 'Monthly Payroll (PKR)',
    profilePhoto: 'Profile Photo',
    nic: 'NIC',
    helper: 'Helper',

    // ── Transport page extras ─────────────────────────────────────────────────
    startNewTrip: 'Start New Trip',
    starting: 'Starting…',
    allTrips: 'All Trips',
    tripDetails: 'Trip Details',
    tripCollections: 'Collections',
    completeTrip: 'Complete Trip',
    startedAt: 'Started',
    endedAt: 'Ended',
    noStops: 'No stops recorded.',
    stopLocation: 'Stop location…',
    noCollections: 'No collections linked.',
    selectTripDetail: 'Select a trip to view details',

    // ── Scheduler page extras ─────────────────────────────────────────────────
    schedulerDesc: 'active schedules · Admin only',
    createSchedule: 'Create Schedule',
    scheduleName: 'Schedule Name',
    reportType: 'Report / Document Type',
    recipients: 'Recipients',
    notificationChannels: 'Notification Channels',
    pause: 'Pause',
    resume: 'Resume',
    deleteSchedule: 'Delete',
    farmerInvoiceSummary: 'Farmer Invoice Summary',
    retailerInvoiceSummary: 'Retailer Invoice Summary',
    collectionSummary: 'Collection Summary',
    deliverySummary: 'Delivery Summary',
    profitLossReport: 'Profit & Loss Report',
    adminOnly: 'Admin Only',
    everyDay: 'Every day',
    schedulerInfoText: 'Schedules define what to send, to whom, and when. The system will automatically dispatch invoices, reports, and summaries via the selected channels.',
  },

  ur: {
    // ── Nav ──────────────────────────────────────────────────────────────────
    dashboard: 'ڈیش بورڈ',
    farmers: 'کسان',
    retailers: 'خوردہ فروش',
    collection: 'جمع آوری',
    delivery: 'ترسیل',
    marketRates: 'بازار کی قیمتیں',
    billing: 'بلنگ اور رسیدیں',
    payments: 'ادائیگیاں',
    reports: 'رپورٹیں',
    accounts: 'حسابات',
    transport: 'ٹرانسپورٹ',
    staff: 'عملہ',
    users: 'صارفین',
    settings: 'ترتیبات',
    scheduler: 'شیڈیولر',
    notifications: 'اطلاعات',
    signOut: 'سائن آؤٹ',

    // ── Settings tabs ─────────────────────────────────────────────────────────
    organization: 'تنظیم',
    subscription: 'سبسکرپشن',

    // ── Auth ─────────────────────────────────────────────────────────────────
    signIn: 'سائن ان',
    signingIn: 'سائن ان ہو رہا ہے...',
    email: 'ای میل',
    password: 'پاس ورڈ',
    forgotPassword: 'پاس ورڈ بھول گئے؟',
    signInToAccount: 'اپنے اکاؤنٹ میں سائن ان کریں',
    inviteOnly: 'رسائی صرف دعوت نامے سے ہے۔ اپنے منتظم سے رابطہ کریں۔',
    invalidCredentials: 'ای میل یا پاس ورڈ غلط ہے',

    // ── Common ────────────────────────────────────────────────────────────────
    save: 'ترتیبات محفوظ کریں',
    saving: 'محفوظ ہو رہا ہے…',
    saved: 'محفوظ ہو گیا!',
    loading: 'لوڈ ہو رہا ہے…',
    cancel: 'منسوخ',
    confirm: 'تصدیق',
    delete: 'حذف',
    edit: 'ترمیم',
    add: 'شامل کریں',
    search: 'تلاش',
    filter: 'فلٹر',
    clearFilters: 'صاف کریں',
    exportPDF: 'پی ڈی ایف',
    exportExcel: 'ایکسل',
    close: 'بند کریں',
    noData: 'کوئی ڈیٹا دستیاب نہیں۔',
    from: 'سے',
    to: 'تک',
    all: 'سب',
    date: 'تاریخ',
    amount: 'رقم',
    quantity: 'مقدار',
    rate: 'قیمت',
    total: 'کل',
    net: 'خالص',
    paid: 'ادا شدہ',
    outstanding: 'زیرِ التوا',
    viewAll: 'سب دیکھیں',
    refresh: 'تازہ کریں',
    today: 'آج',
    thisWeek: 'اس ہفتے',
    thisMonth: 'اس مہینے',
    of: 'میں سے',
    session: 'سیشن',
    actions: 'اقدامات',
    sortAsc: 'صعودی ترتیب',
    sortDesc: 'نزولی ترتیب',
    noResults: 'کوئی نتیجہ نہیں ملا۔',
    rowsPerPage: 'فی صفحہ قطاریں',

    // ── Users page ────────────────────────────────────────────────────────────
    inviteUser: 'صارف مدعو کریں',
    name: 'نام',
    role: 'کردار',
    status: 'حیثیت',
    blocked: 'بلاک',
    active: 'فعال',
    pending: 'دعوت نامہ زیرِ التوا',
    block: 'بلاک کریں',
    unblock: 'بلاک ہٹائیں',
    resetPassword: 'پاس ورڈ ری سیٹ',
    removeUser: 'ہٹائیں',
    copyLink: 'لنک کاپی کریں',
    linkCopied: 'کاپی ہو گیا!',
    you: 'آپ',
    usersPageTitle: 'صارفین',
    usersPageDesc: 'ٹیم کی رسائی منظم کریں — مدعو کریں، بلاک کریں یا کردار تبدیل کریں',
    joinedDate: 'شامل ہوئے',
    permissions: 'اجازتیں',
    permissionsDesc: 'یہ صارف کن صفحات تک رسائی حاصل کر سکتا ہے',
    filterByRole: 'کردار سے فلٹر',
    filterByStatus: 'حالت سے فلٹر',
    savePermissions: 'اجازتیں محفوظ کریں',
    savingPermissions: 'محفوظ ہو رہا ہے…',
    permissionsSaved: 'محفوظ!',
    allPagesAccess: 'اس کردار کے لیے بطور ڈیفالٹ تمام صفحات کی اجازت ہے',
    staffInfo: 'عملے کی معلومات',
    department: 'شعبہ',
    position: 'عہدہ',

    // ── Accept invite ─────────────────────────────────────────────────────────
    acceptInviteTitle: 'پاس ورڈ سیٹ کریں',
    acceptInviteSubtitle: 'اپنا اکاؤنٹ فعال کرنے کے لیے ایک محفوظ پاس ورڈ منتخب کریں۔',
    newPassword: 'نیا پاس ورڈ',
    confirmPassword: 'پاس ورڈ کی تصدیق',
    activateAccount: 'اکاؤنٹ فعال کریں',
    activating: 'فعال ہو رہا ہے…',
    passwordMismatch: 'پاس ورڈ مطابقت نہیں رکھتے۔',
    invalidToken: 'دعوت نامہ غلط یا میعاد ختم ہو گئی۔',

    // ── Branding / Settings ───────────────────────────────────────────────────
    brandName: 'برانڈ نام',
    tagline: 'ٹیگ لائن',
    primaryColor: 'بنیادی رنگ',
    accentColor: 'ثانوی رنگ',
    logo: 'لوگو',
    businessDetails: 'کاروباری تفصیلات',
    address: 'پتہ',
    phone: 'فون',
    websiteLabel: 'ویب سائٹ',
    taxId: 'ٹیکس / NTN نمبر',
    bankDetails: 'بینک تفصیلات',
    bankName: 'بینک کا نام',
    accountNo: 'اکاؤنٹ نمبر',
    iban: 'IBAN',
    invoiceTemplate: 'رسید کا سانچہ',
    signature: 'مجاز دستخط',
    invoicePreview: 'رسید ہیڈر کا پیش منظر',

    // ── Dashboard ─────────────────────────────────────────────────────────────
    live: 'لائیو',
    collectedStat: 'جمع شدہ',
    deliveredStat: 'تقسیم شدہ',
    receivablesStat: 'وصولیاں',
    payablesStat: 'واجبات',
    maundsUnit: 'من',
    maundsFull: 'من',
    trend7Day: '۷ روزہ جمع بمقابلہ تقسیم',
    morning: 'صبح',
    evening: 'شام',
    avgRate: 'اوسط',
    collectionProgress: 'جمع آوری کی پیشرفت',
    deliveryProgress: 'ترسیل کی پیشرفت',
    contractedLabel: 'معاہدہ',
    committedLabel: 'وعدہ',
    todayBalance: 'آج کا توازن',
    collectedMinusDelivered: 'جمع منہا تقسیم',
    netFinancial: 'خالص مالی',
    outstandingAllTime: 'زیرِ التوا (سب وقت)',
    viewMarketRates: 'بازار کی قیمتیں دیکھیں ←',
    perMaund: 'روپے/من',
    farmerCountLabel: 'کسان',
    retailerCountLabel: 'خوردہ فروش',
    unpaidLabel: 'ادا نہیں',
    selectDateLabel: 'تاریخ منتخب کریں',
    dashboardFor: 'ڈیش بورڈ برائے',

    // ── Market Rates ──────────────────────────────────────────────────────────
    latestMorningRate: 'تازہ ترین صبح کی قیمت',
    latestEveningRate: 'تازہ ترین شام کی قیمت',
    setMarketRate: 'بازار کی قیمت مقرر کریں',
    ratePKRMun: 'قیمت (روپے/من)',
    rateHistory: 'قیمتوں کی تاریخ',
    setRate: 'قیمت مقرر کریں',
    noRatesYet: 'ابھی کوئی قیمت مقرر نہیں۔',
    marketTrend: 'بازار کی قیمت کا رجحان (آخری ۳۰ دن)',
    ratePlaceholder: 'مثلاً 9000',

    // ── Accounts ──────────────────────────────────────────────────────────────
    profitLoss: 'نفع و نقصان',
    balanceSheet: 'بیلنس شیٹ',
    totalRevenue: 'کل آمدنی',
    grossProfit: 'مجموعی منافع',
    netProfit: 'خالص منافع',
    totalCosts: 'کل اخراجات',
    revenueSectionTitle: 'آمدنی',
    costsSectionTitle: 'اخراجات',
    summarySection: 'خلاصہ',
    farmerPayouts: 'کسانوں کو ادائیگیاں',
    staffSalaries: 'عملے کی تنخواہیں',
    cashInHand: 'نقد موجود',
    yetToCollect: 'ابھی وصول نہیں',
    assetsReceivables: 'اثاثے / وصولیاں',
    liabilitiesPayables: 'ذمہ داریاں / واجبات',
    payrollSection: 'تنخواہ',
    activeStaff: 'فعال عملہ',
    monthlyPayroll: 'ماہانہ تنخواہ',
    netPositionLabel: 'خالص پوزیشن (وصولیاں منہا واجبات)',
    revenueVsCosts: 'آمدنی بمقابلہ اخراجات',
    assetsVsLiabilities: 'اثاثے بمقابلہ ذمہ داریاں',
    grossProfitVsRevenue: 'مجموعی منافع (آمدنی منہا کسان)',
    netProfitAfterSalaries: 'خالص منافع (تنخواہوں کے بعد)',
    retailerReceivablesLabel: 'خوردہ فروش وصولیاں (ادا نہیں)',
    totalRevenueBilled: 'کل بل شدہ آمدنی',
    revenueCollected: 'وصول شدہ آمدنی',
    farmerPayablesLabel: 'کسان واجبات (ادا نہیں)',
    totalFarmerCostsBilled: 'کل کسان اخراجات بل شدہ',
    farmerCostsPaid: 'ادا شدہ کسان اخراجات',
    members: 'اراکین',
    invoicesLabel: 'رسیدیں',
    retailerInvoicesBilled: 'خوردہ فروش رسیدیں (بل شدہ)',
    collectedPaid: 'وصول شدہ (ادا)',
    staffSalariesEst: 'عملے کی تنخواہیں (تخمینہ)',

    // ── Notifications ─────────────────────────────────────────────────────────
    notificationsTitle: 'اطلاعات',
    notificationsDesc: 'واٹس ایپ، ای میل اور SMS کے ذریعے بھیجے گئے پیغامات',
    channelType: 'چینل',
    whatsapp: 'واٹس ایپ',
    sms: 'ایس ایم ایس',
    markRead: 'پڑھا ہوا',
    markAllRead: 'سب پڑھا ہوا',
    noNotifications: 'ابھی کوئی اطلاع نہیں۔',
    notifAll: 'سب',
    notifUnread: 'نہ پڑھا ہوا',
    message: 'پیغام',
    recipient: 'وصول کنندہ',
    sentAt: 'بھیجا گیا',
    readStatus: 'پڑھا',

    // ── Farmers ───────────────────────────────────────────────────────────────
    addFarmer: 'کسان شامل کریں',
    editFarmer: 'کسان ترمیم',
    farmerDetails: 'کسان کی تفصیلات',
    contractedQty: 'معاہدہ مقدار (من/دن)',
    fixedRate: 'مقررہ قیمت (روپے/من)',
    farmerName: 'کسان کا نام',
    village: 'گاؤں / علاقہ',
    cnic: 'شناختی کارڈ',
    noFarmers: 'کوئی کسان نہیں ملا۔',
    dailyQty: 'یومیہ مقدار',
    contractRate: 'معاہدہ قیمت',

    // ── Retailers ─────────────────────────────────────────────────────────────
    addRetailer: 'خوردہ فروش شامل کریں',
    editRetailer: 'خوردہ فروش ترمیم',
    retailerDetails: 'خوردہ فروش کی تفصیلات',
    committedQty: 'وعدہ مقدار (من/دن)',
    retailerName: 'خوردہ فروش کا نام',
    shopName: 'دکان کا نام',
    area: 'علاقہ',
    noRetailers: 'کوئی خوردہ فروش نہیں ملا۔',

    // ── Collection / Delivery ─────────────────────────────────────────────────
    addCollection: 'جمع آوری شامل کریں',
    addDelivery: 'ترسیل شامل کریں',
    fat: 'چکنائی %',
    waterAdded: 'پانی ملا',
    collectionHistory: 'جمع آوری کی تاریخ',
    deliveryHistory: 'ترسیل کی تاریخ',
    noEntries: 'کوئی اندراج نہیں۔',
    selectFarmer: 'کسان منتخب کریں',
    selectRetailer: 'خوردہ فروش منتخب کریں',
    farmer: 'کسان',
    retailer: 'خوردہ فروش',
    maunds: 'من',
    litres: 'لیٹر',
    quality: 'معیار',
    passed: 'پاس',
    failed: 'ناکام',

    // ── Billing ───────────────────────────────────────────────────────────────
    farmerInvoices: 'کسان رسیدیں',
    retailerInvoices: 'خوردہ فروش رسیدیں',
    generateInvoice: 'رسیدیں بنائیں',
    generating: 'بن رہی ہیں…',
    markAsPaid: 'ادا شدہ',
    paymentMode: 'ادائیگی کا طریقہ',
    paymentRef: 'حوالہ نمبر',
    paymentDate: 'ادائیگی کی تاریخ',
    invoiceNo: 'رسید نمبر',
    invoiceDate: 'رسید کی تاریخ',
    dueDate: 'آخری تاریخ',
    penalty: 'جرمانہ',
    bonus: 'انعام',
    netPayable: 'خالص واجب الادا',
    invoiceStatus: 'حیثیت',
    noInvoices: 'کوئی رسید نہیں۔',
    paidInvoices: 'ادا شدہ',
    unpaidInvoices: 'ادا نہیں',
    totalBilled: 'کل بل',
    totalPaid: 'کل ادا',
    totalOutstanding: 'کل زیرِ التوا',
    netPayableWords: 'خالص واجب الادا بالفاظ',
    dateWise: 'تاریخ وار تفصیل',
    morningQty: 'صبح مقدار',
    eveningQty: 'شام مقدار',
    marketRateApplied: 'بازار قیمت لاگو',
    fixedRateApplied: 'مقررہ قیمت لاگو',
    penaltyApplied: 'جرمانہ لاگو',
    rewardApplied: 'انعام لاگو',
    penaltyQty: 'جرمانہ مقدار',
    rewardQty: 'انعام مقدار',

    // ── Payments ──────────────────────────────────────────────────────────────
    addPayment: 'ادائیگی شامل کریں',
    paymentDirection: 'سمت',
    incoming: 'آنے والی',
    outgoing: 'جانے والی',
    noPayments: 'کوئی ادائیگی نہیں۔',
    paymentSummary: 'ادائیگی کا خلاصہ',
    totalIncoming: 'کل آنے والی',
    totalOutgoing: 'کل جانے والی',
    balance: 'توازن',

    // ── Reports ───────────────────────────────────────────────────────────────
    generateReport: 'رپورٹ بنائیں',
    selectReport: 'رپورٹ کی قسم منتخب کریں',
    dateRange: 'تاریخ کی حد',
    collectionReport: 'جمع آوری رپورٹ',
    deliveryReport: 'ترسیل رپورٹ',
    qualityReport: 'معیار رپورٹ',
    paymentsReport: 'ادائیگی رپورٹ',
    receivablesReport: 'وصولیاں رپورٹ',
    payablesReport: 'واجبات رپورٹ',
    balanceReport: 'توازن رپورٹ',
    noReport: 'رپورٹ بنانے کے لیے قسم اور تاریخ منتخب کریں۔',
    downloading: 'ڈاؤن لوڈ ہو رہا ہے…',

    // ── Transport ─────────────────────────────────────────────────────────────
    addTrip: 'سفر شامل کریں',
    tripDate: 'سفر کی تاریخ',
    driver: 'ڈرائیور',
    route: 'راستہ',
    stops: 'پڑاؤ',
    tripStatus: 'حیثیت',
    addTank: 'ٹینک شامل کریں',
    tankCapacity: 'گنجائش (لیٹر)',
    noTrips: 'کوئی سفر نہیں۔',
    noTanks: 'کوئی ٹینک نہیں۔',

    // ── Staff ─────────────────────────────────────────────────────────────────
    addStaff: 'عملہ شامل کریں',
    staffName: 'عملے کا نام',
    staffRole: 'عملے کا کردار',
    salary: 'ماہانہ تنخواہ',
    joiningDate: 'شمولیت کی تاریخ',
    noStaff: 'کوئی عملہ نہیں۔',
    payroll: 'تنخواہ',
    totalPayroll: 'کل تنخواہ',

    // ── Scheduler ─────────────────────────────────────────────────────────────
    addSchedule: 'شیڈول شامل کریں',
    frequency: 'تعدد',
    nextRun: 'اگلی بار',
    scheduleType: 'شیڈول کی قسم',
    noSchedules: 'کوئی شیڈول نہیں۔',
    toggleSchedule: 'تبدیل',
    daily: 'روزانہ',
    weekly: 'ہفتہ وار',
    monthly: 'ماہانہ',
    enabled: 'فعال',
    disabled: 'غیر فعال',
    lastRun: 'آخری بار',

    // ── Farmers / Retailers ───────────────────────────────────────────────────
    inactive: 'غیر فعال',
    deactivate: 'غیر فعال کریں',
    contractPeriod: 'معاہدہ مدت',
    ongoing: 'جاری',
    phoneEmail: 'فون / ای میل',
    newFarmer: 'نیا کسان',
    updateFarmer: 'کسان اپ ڈیٹ کریں',
    saveFarmer: 'کسان محفوظ کریں',
    newRetailer: 'نیا خوردہ فروش',
    updateRetailer: 'خوردہ فروش اپ ڈیٹ کریں',
    saveRetailer: 'خوردہ فروش محفوظ کریں',
    perDay: '/دن',
    activeCount: 'فعال',
    deactivateConfirm: 'یہ اندراج غیر فعال کریں؟',

    // ── Billing extra ─────────────────────────────────────────────────────────
    allFarmers: 'سب کسان',
    allRetailers: 'سب خوردہ فروش',
    allModes: 'سب طریقے',
    totalInvoices: 'کل رسیدیں',
    totalAmount: 'کل رقم (روپے)',
    baseAmount: 'بنیادی رقم',
    shortfall: 'کمی',
    excess: 'اضافہ',
    surcharge: 'اضافی چارج',
    exportPDFBtn: 'پی ڈی ایف',

    // ── Payments extra ────────────────────────────────────────────────────────
    note: 'نوٹ',
    paymentType: 'قسم',
    cash: 'نقد',
    cheque: 'چیک',
    bankTransfer: 'بینک ٹرانسفر',
    online: 'آن لائن',

    // ── Reports extra ─────────────────────────────────────────────────────────
    morningCollection: 'صبح جمع آوری',
    eveningCollection: 'شام جمع آوری',
    combinedCollection: 'مشترکہ جمع آوری',
    morningDelivery: 'صبح ترسیل',
    eveningDelivery: 'شام ترسیل',
    combinedDelivery: 'مشترکہ ترسیل',
    milkQuality: 'دودھ کا معیار',
    passRate: 'پاس شرح',
    avgFat: 'اوسط چکنائی %',
    totalEntries: 'کل اندراجات',
    receivablesPayables: 'وصولیاں اور واجبات',
    balanceReportLabel: 'توازن رپورٹ',

    // ── Transport extra ───────────────────────────────────────────────────────
    tripNumber: 'سفر نمبر',
    vehicle: 'گاڑی',
    inProgress: 'جاری',
    completed: 'مکمل',
    newTrip: 'نیا سفر',
    tankLabel: 'ٹینک',
    capacity: 'گنجائش (ل)',
    newTank: 'نیا ٹینک',

    // ── Staff extra ───────────────────────────────────────────────────────────
    updateStaff: 'عملہ اپ ڈیٹ کریں',
    saveStaff: 'عملہ محفوظ کریں',
    newStaff: 'نیا عملہ رکن',
    phoneLabel: 'فون',

    // ── Settings extra ────────────────────────────────────────────────────────
    logoUrl: 'لوگو لنک',
    invoiceFooterLabel: 'رسید کا فوٹر',
    invoiceHeaderLabel: 'رسید کا ہیڈر',
    signatureTitle: 'دستخط کا عنوان',
    signatureName: 'دستخط کنندہ کا نام',
    settingsTitle: 'ترتیبات',
    orgTab: 'تنظیم',
    subTab: 'سبسکرپشن',
    planLabel: 'پلان',
    renewsLabel: 'تجدید',

    // ── Collection / Delivery extra ───────────────────────────────────────────
    bulkEntry: 'آج کا اندراج',
    saveEntries: 'اندراجات محفوظ کریں',
    savedCount: 'محفوظ',
    skippedCount: 'چھوڑا گیا',
    totalMorning: 'کل صبح',
    totalEvening: 'کل شام',
    grandTotal: 'کل مجموعہ',
    historyTab: 'تاریخ',
    inputTab: 'اندراج',

    // ── Social login ──────────────────────────────────────────────────────────
    orContinueWith: 'یا جاری رکھیں',
    signInWithGoogle: 'گوگل سے جاری رکھیں',
    signInWithFacebook: 'فیس بک سے جاری رکھیں',
    yes: 'ہاں',
    no: 'نہیں',

    // ── Payments page extras ──────────────────────────────────────────────────
    recordPayment: 'ادائیگی درج کریں',
    recordNewPayment: 'نئی ادائیگی درج کریں',
    savePayment: 'ادائیگی محفوظ کریں',
    referenceNo: 'حوالہ / چیک نمبر',
    notes: 'نوٹس',
    allTypes: 'سب اقسام',
    netPosition: 'خالص پوزیشن',
    party: 'فریق',
    deletePayment: 'ادائیگی حذف کریں؟',
    cannotUndo: 'یہ عمل واپس نہیں ہو سکتا۔',
    gift: 'تحفہ',
    other: 'دیگر',
    allDirections: 'سب سمتیں',

    // ── Staff page extras ─────────────────────────────────────────────────────
    totalActiveStaff: 'کل فعال عملہ',
    monthlyPayrollPKR: 'ماہانہ تنخواہ (روپے)',
    profilePhoto: 'پروفائل تصویر',
    nic: 'شناختی کارڈ نمبر',
    helper: 'مددگار',

    // ── Transport page extras ─────────────────────────────────────────────────
    startNewTrip: 'نیا سفر شروع کریں',
    starting: 'شروع ہو رہا ہے…',
    allTrips: 'تمام سفر',
    tripDetails: 'سفر کی تفصیلات',
    tripCollections: 'جمع آوریاں',
    completeTrip: 'سفر مکمل کریں',
    startedAt: 'شروع',
    endedAt: 'ختم',
    noStops: 'کوئی پڑاؤ نہیں۔',
    stopLocation: 'پڑاؤ کا مقام…',
    noCollections: 'کوئی جمع آوری نہیں۔',
    selectTripDetail: 'تفصیل دیکھنے کے لیے سفر منتخب کریں',

    // ── Scheduler page extras ─────────────────────────────────────────────────
    schedulerDesc: 'فعال شیڈول · صرف منتظم',
    createSchedule: 'شیڈول بنائیں',
    scheduleName: 'شیڈول کا نام',
    reportType: 'رپورٹ / دستاویز کی قسم',
    recipients: 'وصول کنندگان',
    notificationChannels: 'اطلاع کے چینل',
    pause: 'روکیں',
    resume: 'دوبارہ شروع کریں',
    deleteSchedule: 'حذف',
    farmerInvoiceSummary: 'کسان رسید خلاصہ',
    retailerInvoiceSummary: 'خوردہ فروش رسید خلاصہ',
    collectionSummary: 'جمع آوری خلاصہ',
    deliverySummary: 'ترسیل خلاصہ',
    profitLossReport: 'نفع و نقصان رپورٹ',
    adminOnly: 'صرف منتظم',
    everyDay: 'ہر روز',
    schedulerInfoText: 'شیڈول یہ طے کرتا ہے کہ کیا، کسے، اور کب بھیجنا ہے۔ سسٹم خودکار طور پر رسیدیں، رپورٹیں اور خلاصے منتخب چینلز کے ذریعے بھیجے گا۔',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
